name: Gradle and REST Assured sicredi-desafio-api

on:
  push:
    branches: [ "qaautomationSicredi" ]
  pull_request:
    branches: [ "qaautomationSicredi" ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Java
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"

      - name: Build and Run REST Assured sicredi-desafio-api
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Archive REST-Assured results
        uses: actions/upload-artifact@v4
        with:
          name: REST-Assured-results
          path: build/reports/tests/test
      - name: Upload REST-Assured results to GitHub
        uses: actions/upload-artifact@v4
        with:
            name: REST-Assured-results
            path: build/reports/tests/test












