name: Gradle and REST Assured sicredi-desafio-api

on:
  push:
    branches: [ "qaautomationSicredi" ]
  pull_request:
    branches: [ "qaautomationSicredi" ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Java
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests and Generate Allure Results
        run: ./gradlew test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results-${{  github.run_id }}
          path: allure-results













