name: Gradle and REST Assured sicredi-desafio-api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Automacao-sicredi-desafio-api
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Archive REST-Assured results
        uses: actions/upload-artifact@v4
        continue-on-error: true

        with:
          name: REST-Assured-results allure
          path: build/allure-results

      - name: Upload REST-Assured results to GitHub
        uses: actions/upload-artifact@v4
        continue-on-error: true

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.4
        id: allure-report
        if: always()
        with:
              allure-results: allure-results
              website: gh-pages-dir
              reports-site-path: builds/tests












