name: Gradle and REST Assured sicredi-desafio-api

on:
  push:
    branches: [ "qaautomationSicredi" ]
  pull_request:
    branches: [ "qaautomationSicredi" ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build project
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"

     












