name: Gradle and REST Assured sicredi-desafio-api

on:
  push:
    branches: [ "qaautomationSicredi" ]
  pull_request:
    branches: [ "qaautomationSicredi" ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Java
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"

      - name: Archive REST-Assured allure reports
        uses: actions/upload-artifact@v4
        with:
          name: REST-Assured-allure-reports
          path: build/allure-results













